sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KcdDfIJL/PVwrExb3FvOvx5QJVrqXvczldfaHjHsRQZEEfvG4dMDxThjYj5NoEVfNwA2YTLOHi3fOE8W7MOu3FxXBMDJof97OT4fZC7IX6ySbpWU+dwc8ideIPpKaWOlQeirypQK0pO3Bwu7V2fV+h6P6w0mWhx8HOuevIzR8tO830K0ZJKA9/Gdy+iRtDDmuls/E+URCjWe14oq9c2Mnnaa3heLeMlCDdnRuQf84BnbinN9eXuUZdp9FTpEMmR9q3SOoNJ5kQqN4E/w7HopT3hFCzka6pyncj88HYCkkgURXNZyb76wxnV8wZ1YPdkx7AUUuXXf0BwQir9HngQKk1yfKXTgfQsNtDMW0s/3qPOHm6Gh+/RsHw8a0Lrvd6heRFXX+bbf+uPS5p7rv3Yi0ikunWlk/GWWVgM1jPoDxBNJdNLP2OH/mvXkP1QgUG9HthRds8tfR9rAHXbx4pHCyhXSbabR6BVGUSo1msX+N1QDgiP2ZHt5bZGZsFIE3cH0iWGr+7oFpW1oCBvTbWfzaFCZMmLy3xBCw06oAGjEFWiPJh90Fj242OjuGsYsIUzv7oJYebz9K5M3ygtvQcXDIHegVQdGJp5T/Jc6bMRIe1Zn+Ovad7mfj9x5O2GmKljWBcupw7SgtVdokNoPsX1+gBqxTSEr73zzznXpgNfOV78=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tarzan-of-the-Apes_78
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy